"""make database

Revision ID: 9dce2ab7b4be
Revises:
Create Date: 2023-08-17 17:11:22.882347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dce2ab7b4be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('ACTIVITY',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('activity', sa.String(length=256), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['USERS.username'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('GOALS',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.Column('subcategory', sa.String(length=256), nullable=False),
    sa.Column('param_name', sa.String(length=256), nullable=True),
    sa.Column('param_value', sa.Float(precision=6), nullable=True),
    sa.Column('emission', sa.Float(precision=6), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['USERS.username'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('HISTORY',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.Column('subcategory', sa.String(length=256), nullable=False),
    sa.Column('param_name', sa.String(length=256), nullable=True),
    sa.Column('param_value', sa.Float(precision=6), nullable=False),
    sa.Column('emission', sa.Float(precision=6), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['USERS.username'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HISTORY')
    op.drop_table('GOALS')
    op.drop_table('ACTIVITY')
    op.drop_table('USERS')
    # ### end Alembic commands ###
