"""make database

Revision ID: fde6ebabdac4
Revises:
Create Date: 2023-08-13 14:08:09.949006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde6ebabdac4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GROUPS',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('USERS',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('postcode', sa.String(length=6), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ACTIVITY',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('activity', sa.String(length=256), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['USERS.username'], ),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('activity')
    )
    op.create_table('GOALS',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.Column('subcategory', sa.String(length=256), nullable=False),
    sa.Column('param_name', sa.String(length=256), nullable=True),
    sa.Column('param_value', sa.Float(precision=6), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['USERS.username'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('HISTORY',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.Column('subcategory', sa.String(length=256), nullable=False),
    sa.Column('param_name', sa.String(length=256), nullable=True),
    sa.Column('param_value', sa.Float(precision=6), nullable=False),
    sa.Column('emission', sa.Float(precision=6), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['USERS.username'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('MEMBERSHIP',
    sa.Column('membership_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['GROUPS.group_id'], ),
    sa.ForeignKeyConstraint(['username'], ['USERS.username'], ),
    sa.PrimaryKeyConstraint('membership_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MEMBERSHIP')
    op.drop_table('HISTORY')
    op.drop_table('GOALS')
    op.drop_table('ACTIVITY')
    op.drop_table('USERS')
    op.drop_table('GROUPS')
    # ### end Alembic commands ###
